### ISSUE TITLE
Exchanger blocks

### ISSUE THREAD

**Issue by canilsen** [voxelcarrot/EnderTech#43]
Hey! I was wondering if you had plans / solution for blocks not currently being able to be exchanged. In example, some of  the new chisel2 blocks don't work. Anything I can fiddlefaddle with to get it to work?

**Comment by voxelcarrot** [comment]
Hi there. It depends why the block couldn't be exchanged. If it's a tile entity, you won't ever be able to exchange it. Which blocks specifically?

**Comment by canilsen** [comment]
Thanks for a quick reply! The block I was going to use was Laboratory Block Enamelled wall. chisel:laboratoryblock:2. Could it be a meta data issue?

**Comment by voxelcarrot** [comment]
What specifically doesn't work about using these blocks? When you shift+right click to try and select them with the Exchanger, does a red outline show?

**Comment by canilsen** [comment]
You know what? Now that I went to take screenshots to show example, it worked for me. I have no idea what I did wrong before.. Please ignore me, now I feel dumb.
