### ISSUE TITLE
QUESTION about energy usage

### ISSUE THREAD

**Issue by SgtPunishment** [voxelcarrot/EnderTech#47]
I'm currently having a heated discussion about how you work out the total cost for an area with the resonant exchanger, we've managed to work out a range of single block energy usage.

Now we're trying to work out the total usage for a radius (3x3 all the way up to 15x15)

My argument is it's Length X Width X Energy cost per block = total cost result, and he's pulling random numbers out of think air and claiming that his math is right, could you please settle this for us?

**Comment by voxelcarrot** [comment]
The exact formula is in the source, here: https://github.com/voxelcarrot/EnderTech/blob/master/src/main/java/io/endertech/handler/WorldEventHandler.java#L106

**Comment by SgtPunishment** [comment]
I know, that's what we used to get the cost (is it per block, or total for the result?)

**Comment by voxelcarrot** [comment]
The exchange cost is: a base cost + a radius cost + a hardness cost. There's a maximum and a minimum cost, and the final result is clamped to that.

It's per block.

**Comment by SgtPunishment** [comment]
So to get the total cost, say of an 8 block radius (15x15) would it be 15 x 15 x cost per block?

**Comment by voxelcarrot** [comment]
No, it's per block. So the cost of doing the 'inner' exchanges at radius 1 are cheaper than the exchanges at radius 15, in the same exchange. It's to discourage people doing enormous single exchanges (many smaller exchanges are cheaper than the same single 'large' exchange). Make sense?

**Comment by SgtPunishment** [comment]
so it builds up over time?

**Comment by voxelcarrot** [comment]
Within the same exchange, yes.

**Comment by SgtPunishment** [comment]
Interesting, I didn't think of it like that

**Comment by SgtPunishment** [comment]
Okay, you've settled the argument, now I'm having to deal with an ego-maniac now lol
